'use client';
import SiteHeader from './SiteHeader';
import CourseThumbnail from './CourseThumbnail';
import CourseHeroVisual from './CourseHeroVisual';
import TextPressure from './TextPressure';
import Grainient from './Grainient';

import { useEffect, useMemo, useRef, useState } from 'react';
import { SiteFooter } from './SharedSiteSections';

const smartInvestingModules = [
  ['Introduction to the Stock Market', ['What is the Stock Market?', 'Why does the Stock Market exist?', 'History of the Indian Stock Market', 'Difference between Saving and Investing', 'Wealth Creation through Investing', 'Common Myths about Stock Market', 'Types of Investors', 'Financial Goals and Investing'], 'After completing this module, students will understand why stock markets exist and how they help in wealth creation.'],
  ['How the Stock Market Works', ['Primary Market', 'Secondary Market', 'IPO Explained', 'Follow-on Public Offer (FPO)', 'Rights Issue', 'Bonus Shares', 'Stock Exchanges', 'NSE vs BSE', 'Market Timings', 'Trading Holidays', 'Settlement Cycle (T+1)'], 'See how a company such as Tata Motors gets listed on NSE and how a trade moves through the market.'],
  ['Stock Market Participants', ['Retail Investors', 'Institutional Investors', 'Foreign Institutional Investors (FIIs)', 'Domestic Institutional Investors (DIIs)', 'Mutual Funds', 'Market Makers', 'Brokers', 'Depositories', 'Regulators (SEBI)'], 'Understand who participates in the market and how FIIs and DIIs can affect it.'],
  ['Demat and Trading Account', ['What is a Demat Account?', 'Trading Account', 'Bank Account Linkage', 'How Shares are Stored', 'Depository Participants', 'KYC Process', 'Opening an Account', 'Charges Explained'], 'Complete a practical, step-by-step walkthrough of opening a Demat account.'],
  ['Types of Financial Instruments', ['Equity Shares', 'Preference Shares', 'Bonds', 'Government Securities', 'ETFs', 'Mutual Funds', 'REITs', 'InvITs', 'Gold ETFs', 'Sovereign Gold Bonds'], 'Understand where each investment instrument fits in a portfolio.'],
  ['Understanding Stocks', ['What is a Share?', 'Face Value', 'Market Price', 'Market Capitalization', 'Large Cap', 'Mid Cap', 'Small Cap', 'Blue-chip Stocks', 'Growth Stocks', 'Value Stocks', 'Dividend Stocks'], 'Identify companies across stock categories and begin reading their market characteristics.'],
  ['Understanding Stock Prices', ['Why Prices Move', 'Demand & Supply', 'Circuit Limits', 'Upper Circuit', 'Lower Circuit', 'Volume', 'Liquidity', 'Volatility', 'Bid Price', 'Ask Price', 'Spread'], 'Use Reliance as a practical example to understand why prices can change every second.'],
  ['Basic Fundamental Analysis', ['Company Financial Statements', 'Revenue', 'Profit', 'EPS', 'PE Ratio', 'PB Ratio', 'ROE', 'Debt to Equity', 'Book Value', 'Cash Flow', 'Promoter Holding'], 'Analyse a listed company using a focused set of fundamental indicators.'],
  ['Introduction to Technical Analysis', ['Price Charts', 'Line Chart', 'Bar Chart', 'Candlestick Chart', 'Time Frames', 'Support', 'Resistance', 'Trend Lines', 'Moving Averages', 'RSI', 'MACD'], 'Read live charts and recognise the technical building blocks behind a market view.'],
  ['Order Types', ['Market Order', 'Limit Order', 'Stop Loss', 'Stop Limit', 'Bracket Order', 'Cover Order', 'GTT Orders', 'AMO Orders'], 'Place and compare different order types in a guided demo.'],
  ['Risk Management', ['Risk vs Reward', 'Position Sizing', 'Diversification', 'Portfolio Allocation', 'Stop Loss Strategy', 'Capital Protection', 'Emotional Discipline'], 'Protect capital before chasing profits by applying a practical risk framework.'],
  ['Long-Term Investing', ['Power of Compounding', 'SIP', 'Lump Sum Investing', 'Dividend Reinvestment', 'Goal-Based Investing', 'Portfolio Building', 'Asset Allocation'], 'Apply long-term investing principles to a ₹5,000 monthly investment over 20 years.'],
  ['Common Beginner Mistakes', ['FOMO Buying', 'Panic Selling', 'Overtrading', 'Tips & Rumours', 'Leverage Misuse', 'No Risk Management', 'Lack of Research'], 'Avoid the mistakes that most new investors make when they first enter the market.'],
  ['Live Market Demonstration', ['Reading Live Market', 'Understanding Market Depth', 'Identifying Trending Stocks', 'Watching Price Action', 'Placing Your First Trade'], 'Complete a live walkthrough of a trading platform with an instructor.'],
  ['Building Your First Portfolio', ['Selecting Stocks', 'Diversification', 'Sector Allocation', 'Rebalancing', 'Long-Term Strategy', 'Tracking Performance', 'Exit Strategy'], 'Create a ₹1 lakh model portfolio and explain the investment rationale behind it.'],
].map(([title, topics, outcome], index) => ({ title, topics, outcome, duration: `${35 + (index % 3) * 10} min` }));

const mutualFundModules = [
  ['Introduction to Mutual Funds', ['What is a Mutual Fund?', 'Why Mutual Funds are Popular', 'How Mutual Funds Work', 'Benefits of Mutual Fund Investing', 'Myths About Mutual Funds', 'Investment Objectives', 'Wealth Creation Through Mutual Funds'], 'Understand the fundamentals of mutual funds and their role in financial planning.'],
  ['Key Participants in the Mutual Fund Industry', ['Asset Management Companies (AMCs)', 'Fund Managers', 'Trustees', 'Custodians', 'Registrars & Transfer Agents (RTAs)', 'Distributors', 'Investment Advisors', 'Role of SEBI and AMFI'], 'See how money flows from an investor into a mutual fund and gets invested.'],
  ['Types of Mutual Funds', ['Equity Funds', 'Large Cap Funds', 'Mid Cap Funds', 'Small Cap Funds', 'Flexi Cap Funds', 'Multi Cap Funds', 'ELSS Funds', 'Sectoral & Thematic Funds', 'Focused Funds', 'Value Funds', 'Debt Funds', 'Liquid Funds', 'Ultra Short Duration Funds', 'Short Duration Funds', 'Corporate Bond Funds', 'Banking & PSU Funds', 'Gilt Funds', 'Dynamic Bond Funds', 'Hybrid Funds', 'Aggressive Hybrid', 'Balanced Advantage Funds', 'Multi Asset Funds', 'Equity Savings Funds', 'Arbitrage Funds', 'Index Funds', 'ETFs', 'International Funds', 'Fund of Funds'], 'Compare mutual fund categories and recognise the role each category can play for different investment goals.'],
  ['Understanding Mutual Fund Documents', ['Scheme Information Document (SID)', 'Key Information Memorandum (KIM)', 'Factsheet', 'Annual Reports', 'Portfolio Disclosure', 'Riskometer', 'Fund Objectives'], 'Read and interpret a real mutual fund factsheet with confidence.'],
  ['Understanding NAV and Returns', ['What is NAV?', 'How NAV is Calculated', 'Growth Option vs IDCW (Dividend) Option', 'Absolute Return', 'Annualized Return', 'CAGR', 'XIRR', 'Rolling Returns'], 'Calculate and compare returns from a sample mutual fund investment.'],
  ['Risk and Performance Analysis', ['Risk vs Return', 'Volatility', 'Standard Deviation', 'Beta', 'Alpha', 'Sharpe Ratio', 'Sortino Ratio', 'Expense Ratio', 'Portfolio Turnover Ratio'], 'Learn to evaluate whether a fund is worth investing in.'],
  ['Choosing the Right Mutual Fund', ['Matching Funds to Financial Goals', 'Investment Horizon', 'Risk Profile Assessment', 'Comparing Similar Funds', 'Fund House Reputation', 'Consistency of Performance', 'Portfolio Holdings', 'Exit Load Considerations'], 'Select suitable mutual funds for different investor profiles using a structured comparison.'],
  ['SIP, STP & SWP', ['Systematic Investment Plan (SIP)', 'Benefits of SIP', 'Lump Sum Investment', 'Systematic Transfer Plan (STP)', 'Systematic Withdrawal Plan (SWP)', 'Power of Rupee Cost Averaging', 'Power of Compounding'], 'Apply SIP, STP and SWP concepts to a ₹5,000 monthly SIP over 20 years.'],
  ['Taxation of Mutual Funds', ['Equity Fund Taxation', 'Debt Fund Taxation', 'Capital Gains', 'Short-Term Capital Gains', 'Long-Term Capital Gains', 'Tax Harvesting', 'TDS Rules', 'ELSS Tax Benefits'], 'Compare post-tax returns across investment options and understand the tax factors in fund selection.'],
  ['Mutual Fund Platforms & Investment Process', ['Direct vs Regular Plans', 'Online Investment Platforms', 'KYC Process', 'Nomination', 'Account Statements', 'Portfolio Tracking', 'Redemption Process'], 'Complete a mutual fund investment journey from registration to redemption.'],
  ['Portfolio Construction', ['Asset Allocation', 'Diversification', 'Goal-Based Investing', 'Emergency Fund Allocation', 'Retirement Planning', 'Child Education Planning', 'Portfolio Rebalancing'], 'Build a diversified mutual fund portfolio for different financial goals.'],
  ['Common Mistakes to Avoid', ['Chasing High Returns', 'Ignoring Risk', 'Frequent Switching', 'Investing Without Goals', 'Stopping SIPs During Market Falls', 'Following Market Rumours', 'Overlapping Funds', 'Ignoring Expense Ratios'], 'Develop disciplined investing habits and avoid common mutual fund mistakes.'],
  ['Live Fund Analysis', ['Comparing Multiple Funds', 'Reading Factsheets', 'Evaluating Portfolio Holdings', 'Performance Comparison', 'Risk Analysis', 'Selecting the Most Suitable Fund'], 'Analyse real mutual funds using publicly available data.'],
  ['Advanced Mutual Fund Strategies', ['Core & Satellite Portfolio', 'Goal-Based Investing Strategy', 'SIP Top-Up Strategy', 'Retirement Income Strategy', 'Children’s Education Planning', 'Wealth Preservation', 'Inflation-Protected Investing'], 'Use advanced strategies to build and preserve long-term wealth through mutual funds.'],
].map(([title, topics, outcome], index) => ({ title, topics, outcome, duration: `${40 + (index % 3) * 10} min` }));

const createModules = (items, baseDuration = 45) => items.map(([title, topics, outcome], index) => ({ title, topics: topics.split('|'), outcome: outcome ?? `Apply ${title.toLowerCase()} through structured analysis and practical examples.`, duration: `${baseDuration + (index % 3) * 10} min` }));

const technicalAnalysisModules = createModules([
  ['Introduction to Technical Analysis', 'What is Technical Analysis?|Technical Analysis vs Fundamental Analysis|History of Technical Analysis|Dow Theory Explained|Market Psychology|Assumptions of Technical Analysis|Why Charts Work|Common Myths About Technical Analysis', 'Understand the principles behind technical analysis and how market psychology influences price movement.'],
  ['Understanding Price Charts', 'Types of Charts|Line Chart|Bar Chart|Candlestick Chart|Heikin Ashi Chart|Renko Chart|Chart Timeframes|Multiple Timeframe Analysis|Open, High, Low, Close (OHLC)|Volume Basics', 'Compare the same stock across multiple chart types and timeframes.'],
  ['Candlestick Analysis', 'Candlestick Anatomy|Doji|Hammer|Hanging Man|Shooting Star|Marubozu|Bullish Engulfing|Bearish Engulfing|Harami|Morning Star|Evening Star|Three White Soldiers|Three Black Crows', 'Identify reversal and continuation patterns on live charts.'],
  ['Trend Analysis', 'What is a Trend?|Uptrend|Downtrend|Sideways Market|Higher Highs & Higher Lows|Lower Highs & Lower Lows|Trend Reversal|Trend Continuation|Trend Strength', 'Draw and validate trends using historical price charts.'],
  ['Support & Resistance', 'Horizontal Support|Horizontal Resistance|Dynamic Support & Resistance|Trendline Support|Psychological Levels|Breakouts|False Breakouts|Retests|Supply & Demand Zones', 'Mark key support and resistance levels on real stocks.'],
  ['Trendlines & Chart Patterns', 'Drawing Trendlines|Channels|Triangles|Flags|Pennants|Wedges|Rectangles|Cup & Handle|Double Top|Double Bottom|Head & Shoulders|Inverse Head & Shoulders', 'Recognize classic chart formations and understand their implications.'],
  ['Volume Analysis', 'Importance of Volume|Volume Confirmation|Volume Breakouts|Volume Divergence|Delivery Volume|Volume Spikes|Accumulation & Distribution', 'Analyze volume to confirm price movements.'],
  ['Moving Averages', 'Simple Moving Average (SMA)|Exponential Moving Average (EMA)|Weighted Moving Average (WMA)|Moving Average Crossovers|Dynamic Support & Resistance|Golden Cross|Death Cross', 'Build trend-following strategies using moving averages.'],
  ['Momentum Indicators', 'Relative Strength Index (RSI)|Moving Average Convergence Divergence (MACD)|Stochastic Oscillator|Commodity Channel Index (CCI)|Momentum Indicator|Williams %R', 'Use indicators to identify momentum shifts.'],
  ['Volatility Indicators', 'Bollinger Bands|Average True Range (ATR)|Keltner Channels|Donchian Channels|Volatility Breakouts', 'Measure market volatility and adapt trading strategies accordingly.'],
  ['Fibonacci Analysis', 'Fibonacci Retracement|Fibonacci Extension|Fibonacci Expansion|Common Retracement Levels|Combining Fibonacci with Price Action', 'Draw Fibonacci levels on trending stocks.'],
  ['Price Action Trading', 'Reading Pure Price Action|Swing Highs & Swing Lows|Break of Structure (BOS)|Change of Character (CHOCH)|Pullback Trading|Reversal Trading|Continuation Trading|Market Structure', 'Analyze charts without relying on indicators.'],
  ['Trading Strategies', 'Breakout Strategy|Pullback Strategy|Trend Following Strategy|Range Trading|Swing Trading|Positional Trading|Momentum Trading|Gap Trading', 'Backtest multiple trading strategies using historical charts.'],
  ['Risk & Trade Management', 'Position Sizing|Stop Loss Placement|Risk-Reward Ratio|Capital Allocation|Trade Planning|Managing Open Positions|Scaling In & Out|Trading Journal', 'Protect capital while maximizing long-term profitability.'],
  ['Multi-Timeframe Analysis', 'Top-Down Analysis|Aligning Long-Term and Short-Term Trends|Entry & Exit Refinement|Avoiding Conflicting Signals', 'Analyze the same stock on daily, 4-hour, and 15-minute charts.'],
  ['Combining Technical & Fundamental Analysis', 'When to Use Technical Analysis|When to Use Fundamental Analysis|Screening Quality Stocks|Timing Entries Using Charts|Building a Complete Investment Framework', 'Combine business quality with chart-based timing in one investment framework.'],
  ['Live Market Analysis', 'Reading Live Charts|Identifying Trade Setups|Real-Time Decision Making|Trade Execution|Reviewing Winning and Losing Trades', 'Participate in guided chart analysis sessions using current market examples.'],
]);

const optionsTradingModules = createModules([
  ['Introduction to Options Trading', 'What are Options?|Why Options Exist|Difference Between Stocks, Futures & Options|Benefits and Risks of Options Trading|Key Terminology|Understanding Option Contracts|How Options are Used by Traders and Investors', 'Build a solid foundation of options trading concepts and terminology.'],
  ['Basics of Option Contracts', 'Call Options|Put Options|Strike Price|Premium|Expiry Date|Lot Size|Intrinsic Value|Extrinsic (Time) Value|In-the-Money (ITM)|At-the-Money (ATM)|Out-of-the-Money (OTM)', 'Understand option pricing using real market examples.'],
  ['Understanding Option Pricing', 'Components of Premium|Time Decay (Theta)|Implied Volatility (IV)|Historical Volatility (HV)|Open Interest (OI)|Volume|Factors Affecting Option Prices', 'Compare option premiums under different market conditions.'],
  ['The Option Greeks', 'Delta|Gamma|Theta|Vega|Rho|Delta Hedging|Understanding Greek Interactions', 'Analyze how Greeks influence option prices throughout a trade.'],
  ['Option Chain Analysis', 'Reading the Option Chain|Open Interest Analysis|Change in Open Interest|PCR (Put-Call Ratio)|Max Pain Theory|Identifying Support & Resistance Through OI|Option Chain Interpretation', 'Analyze live option chains and identify potential market direction.'],
  ['Buying Options', 'Buying Call Options|Buying Put Options|Trend-Based Entries|Selecting the Right Strike Price|Managing Risk|Profit Targets|Exit Planning', 'Understand when buying options is appropriate and how to manage trades effectively.'],
  ['Option Selling (Writing)', 'Selling Call Options|Selling Put Options|Margin Requirements|Time Decay Advantage|Risk Management|Covered vs Naked Selling|Income Generation Strategies', 'Learn how option sellers capitalize on time decay while managing risk.'],
  ['Single-Leg Option Strategies', 'Long Call|Long Put|Short Call|Short Put|Covered Call|Protective Put', 'Evaluate the payoff and risk profile of each strategy.'],
  ['Multi-Leg Option Strategies', 'Bull Call Spread|Bear Put Spread|Bull Put Spread|Bear Call Spread|Long Straddle|Short Straddle|Long Strangle|Short Strangle|Butterfly Spread|Iron Butterfly|Iron Condor|Calendar Spread|Diagonal Spread', 'Build strategies based on different market outlooks.'],
  ['Volatility-Based Trading', 'Implied Volatility (IV)|IV Rank|IV Percentile|Volatility Crush|Event-Based Trading|Earnings Strategies|Selecting Strategies Based on Volatility', 'Use volatility as a key factor in selecting option strategies.'],
  ['Risk Management in Options Trading', 'Position Sizing|Risk-Reward Analysis|Stop-Loss Techniques|Capital Allocation|Managing Losing Trades|Avoiding Overleveraging|Portfolio Risk', 'Create a structured risk management plan.'],
  ['Trading Psychology', 'Emotional Discipline|Fear and Greed|Patience|Overtrading|Revenge Trading|Building a Trading Routine', 'Develop the mindset needed for consistent trading.'],
  ['Technical Analysis for Options Traders', 'Trend Analysis|Support & Resistance|Candlestick Patterns|Moving Averages|RSI|MACD|Volume Confirmation|Entry & Exit Timing', 'Combine technical analysis with options strategies for higher-probability trades.'],
  ['Live Options Trading Workflow', 'Daily Market Preparation|Selecting Stocks and Indices|Option Chain Review|Strategy Selection|Trade Execution|Position Monitoring|Exit Decisions|Post-Trade Analysis', 'Complete a walkthrough of planning and executing an options trade.'],
  ['Advanced Options Strategies', 'Hedging with Options|Portfolio Protection|Delta-Neutral Strategies|Adjusting Multi-Leg Positions|Rolling Positions|Income-Based Option Strategies|Advanced Trade Adjustments', 'Handle complex market conditions using advanced options techniques.'],
]);

const valueInvestingModules = createModules([
  ['Introduction to Fundamental Analysis', 'What is Fundamental Analysis?|Why Fundamental Analysis Matters|Fundamental vs Technical Analysis|Long-Term Investing Principles|Types of Investors|Growth Investing vs Value Investing|Business Ownership Mindset', 'Understand why successful long-term investors focus on business fundamentals rather than short-term price movements.'],
  ['Understanding Businesses & Industries', 'How Businesses Generate Revenue|Business Models Explained|Industry Analysis|Sector Classification|Cyclical vs Defensive Industries|Competitive Landscape|Economic Moats|Market Leadership', 'Compare companies from different industries and identify their business strengths.'],
  ['Financial Statements Made Simple', 'Introduction to Financial Statements|Income Statement|Balance Sheet|Cash Flow Statement|Notes to Accounts|Annual Reports|Quarterly Results', 'Read and interpret the financial statements of a listed company.'],
  ['Income Statement Analysis', 'Revenue|Cost of Goods Sold (COGS)|Gross Profit|Operating Expenses|EBITDA|Operating Profit (EBIT)|Net Profit|Earnings Per Share (EPS)|Profit Margins', 'Analyze the profitability of a company over multiple years.'],
  ['Balance Sheet Analysis', 'Assets|Liabilities|Shareholders’ Equity|Working Capital|Current Assets|Current Liabilities|Long-Term Debt|Book Value|Capital Structure', 'Evaluate a company’s financial strength and stability.'],
  ['Cash Flow Analysis', 'Operating Cash Flow|Investing Cash Flow|Financing Cash Flow|Free Cash Flow (FCF)|Cash Flow vs Profit|Capital Expenditure (CapEx)|Cash Conversion Cycle', 'Assess the cash-generating ability of a business.'],
  ['Financial Ratios', 'Profitability Ratios|Return on Equity (ROE)|Return on Assets (ROA)|Return on Capital Employed (ROCE)|Net Profit Margin|Operating Margin|Price-to-Earnings (P/E)|Price-to-Book (P/B)|EV/EBITDA|PEG Ratio|Current Ratio|Quick Ratio|Debt-to-Equity|Interest Coverage Ratio|Asset Turnover|Inventory Turnover|Receivables Turnover', 'Compare key financial ratios across companies in the same sector.'],
  ['Valuation Techniques', 'Intrinsic Value|Margin of Safety|Discounted Cash Flow (DCF)|Relative Valuation|Peer Comparison|Dividend Discount Model (DDM)|Earnings Yield', 'Estimate the fair value of a company using different valuation methods.'],
  ['Qualitative Analysis', 'Promoter Quality|Corporate Governance|Management Integrity|Brand Value|Competitive Advantage|Customer Loyalty|Innovation|ESG Considerations', 'Assess non-financial factors that contribute to long-term business success.'],
  ['Annual Report Analysis', 'Chairman’s Letter|Management Discussion & Analysis (MD&A)|Auditor’s Report|Shareholding Pattern|Related Party Transactions|Risk Factors|Future Outlook', 'Analyze a complete annual report and identify key investment insights.'],
  ['Economic & Industry Analysis', 'GDP and Economic Growth|Inflation|Interest Rates|Government Policies|Industry Cycles|Global Events|Commodity Prices|Currency Movements', 'Understand how macroeconomic factors influence business performance.'],
  ['Stock Screening', 'Building a Stock Screener|Selecting Financial Filters|Growth Stocks|Value Stocks|Dividend Stocks|Small-Cap Opportunities|Quality Businesses', 'Create a watchlist using screening criteria.'],
  ['Portfolio Construction', 'Diversification|Asset Allocation|Sector Allocation|Position Sizing|Risk Management|Rebalancing|Long-Term Portfolio Strategy', 'Design a balanced portfolio aligned with financial goals.'],
  ['Common Fundamental Analysis Mistakes', 'Buying Based on Tips|Ignoring Cash Flow|Focusing Only on P/E Ratio|Overlooking Debt Levels|Misreading Financial Statements|Falling for Market Hype|Lack of Diversification', 'Review poor investment decisions and identify what went wrong.'],
  ['Live Company Analysis', 'Industry Research|Financial Statement Review|Ratio Analysis|Valuation|Competitive Comparison|Investment Decision Framework', 'Conduct a complete analysis of a listed company from start to finish.'],
]);

const equityResearchModules = createModules([
  ['Introduction to Equity Research', 'What is Equity Research?|Role of a Research Analyst|Buy-Side vs Sell-Side Research|Research Process Overview|Career Opportunities|Responsibilities of a Research Analyst|Industry Standards', 'Understand the role, responsibilities, and career path of a professional equity research analyst.'],
  ['Understanding Financial Markets', 'Indian Capital Markets|Equity Markets|Debt Markets|Derivatives Market|Mutual Funds|Market Participants|Stock Exchanges|Market Infrastructure'],
  ['Business & Industry Analysis', 'Business Models|Industry Life Cycle|Sector Analysis|Competitive Landscape|Porter’s Five Forces|SWOT Analysis|Economic Moats', 'Analyze different industries and compare leading companies.'],
  ['Financial Statement Analysis', 'Income Statement|Balance Sheet|Cash Flow Statement|Notes to Accounts|Annual Reports|Quarterly Results|Financial Red Flags', 'Analyze the financial statements of a listed company.'],
  ['Ratio Analysis', 'Profitability Ratios|Liquidity Ratios|Solvency Ratios|Efficiency Ratios|Valuation Ratios|Growth Ratios|Cash Flow Ratios', 'Calculate and interpret financial ratios for investment decisions.'],
  ['Company Valuation', 'Intrinsic Value|Discounted Cash Flow (DCF)|Relative Valuation|Comparable Company Analysis|EV/EBITDA|P/E Valuation|PEG Ratio|Sum-of-the-Parts Valuation', 'Estimate the fair value of a business using multiple valuation techniques.'],
  ['Financial Modeling', 'Excel for Equity Research|Revenue Forecasting|Cost Projections|Profit Forecasting|Cash Flow Forecasting|Integrated Financial Models|Scenario & Sensitivity Analysis', 'Build a financial model from scratch.'],
  ['Equity Research Report Writing', 'Structure of a Research Report|Investment Thesis|Business Overview|Industry Outlook|Financial Analysis|Valuation Summary|Risk Factors|Buy/Hold/Sell Recommendation|Mandatory Disclosures', 'Write a professional equity research report.'],
  ['Technical Analysis for Research Analysts', 'Trend Analysis|Support & Resistance|Candlestick Patterns|Volume Analysis|Moving Averages|RSI|MACD|Entry & Exit Timing'],
  ['Economic & Macro Analysis', 'GDP|Inflation|Interest Rates|RBI Monetary Policy|Fiscal Policy|Exchange Rates|Commodity Prices|Global Events', 'Understand how macroeconomic factors influence equity markets.'],
  ['SEBI Research Analyst Regulations', 'Overview of the SEBI (Research Analysts) Regulations|Registration Categories|Eligibility Criteria|Qualification & Certification Requirements|Research Reports|Conflict of Interest|Code of Conduct|Disclosure Requirements|Investor Protection', 'Understand regulatory responsibilities and professional standards expected of research analysts.'],
  ['Registration Process', 'Educational Eligibility|Required Certifications|NISM Research Analyst Certification|Application Process|Documentation|Fees|Registration Workflow|Renewal Requirements', 'Walk through the registration process and required documentation; always verify current SEBI and NISM requirements before applying.'],
  ['Ethics & Professional Standards', 'Research Ethics|Insider Trading|Chinese Walls|Confidential Information|Conflict Management|Fair Research Practices|Investor Protection|Compliance Culture'],
  ['Research Tools & Data Platforms', 'Annual Reports|Investor Presentations|Corporate Filings|Earnings Calls|Stock Screeners|Financial Databases|Economic Calendars|Market News Sources'],
  ['Practical Equity Research', 'Company Selection|Industry Research|Financial Analysis|Valuation|Investment Recommendation|Risk Analysis|Report Presentation', 'Prepare a complete equity research report on a listed company.'],
]);

const nismModules = createModules([
  ['Introduction to Research Analyst Profession', 'Role of a Research Analyst|Responsibilities|Skills Required|Career Opportunities|Buy-Side vs Sell-Side Research|Ethics and Professional Conduct'],
  ['Introduction to Securities Market', 'Financial Markets|Equity Markets|Debt Markets|Derivatives|Mutual Funds|ETFs|Primary Market|Secondary Market|Market Participants|SEBI|Stock Exchanges'],
  ['Financial Statement Analysis', 'Income Statement|Balance Sheet|Cash Flow Statement|Annual Reports|Quarterly Reports|Notes to Accounts|Financial Red Flags', 'Analyze a listed company’s financial statements.'],
  ['Ratio Analysis', 'EPS|P/E Ratio|P/B Ratio|ROE|ROCE|Debt-to-Equity|Current Ratio|Quick Ratio|Profit Margins|Asset Turnover'],
  ['Company & Industry Analysis', 'Business Models|Industry Structure|Porter’s Five Forces|SWOT Analysis|Economic Moats|Competitive Analysis|Sector Comparison'],
  ['Equity Valuation', 'Intrinsic Value|Margin of Safety|DCF Valuation|Relative Valuation|EV/EBITDA|Dividend Discount Model|PEG Ratio'],
  ['Investment Decision Making', 'Growth Investing|Value Investing|Dividend Investing|Portfolio Diversification|Asset Allocation|Investment Thesis|Risk Assessment'],
  ['Economics & Macroeconomic Analysis', 'GDP|Inflation|Interest Rates|RBI Policy|Fiscal Policy|Exchange Rates|Commodity Prices|Economic Indicators'],
  ['Technical Analysis', 'Dow Theory|Candlestick Charts|Trend Analysis|Support & Resistance|Trendlines|Moving Averages|RSI|MACD|Chart Patterns|Volume Analysis'],
  ['Research Report Writing', 'Structure of a Research Report|Investment Thesis|Company Overview|Industry Analysis|Valuation|Recommendation|Risk Factors|Mandatory Disclosures', 'Write a complete equity research report.'],
  ['Legal & Regulatory Framework', 'SEBI (Research Analysts) Regulations|Code of Conduct|Conflict of Interest|Disclosure Requirements|Compliance Standards|Investor Protection|ASM & GSM Framework'],
  ['Excel for Research Analysts', 'Financial Modeling Basics|Forecasting|Valuation Models|Ratio Analysis in Excel|Charts & Dashboards|Scenario Analysis'],
  ['Mock Tests & Case Studies', 'Chapter-Wise Practice Tests|Full-Length Mock Exams|Case-Based Questions|Previous Pattern Questions|Time Management Techniques|Exam Strategy'],
]);

const courses = [
  { slug: 'smart-investing-fundamentals', title: 'Smart Investing Fundamentals', subtitle: "Beginner's Guide to Stock Market", level: 'Beginner', duration: '15 modules', video: 'course-investing.mp4', description: 'Build a strong investing foundation—from how markets work and opening a Demat account to portfolio building, risk and live market practice.', modules: smartInvestingModules },
  { slug: 'mutual-fund-wealth-builder', title: 'Mutual Fund Wealth Builder', subtitle: 'Mutual Fund Blueprint', level: 'Beginner to intermediate', duration: '10–15 hours', video: 'course-mutual-funds.mp4', description: 'Learn how mutual funds work, compare fund categories, analyse performance, manage risk, optimise taxes, and build a long-term wealth creation strategy.', modules: mutualFundModules },
  { slug: 'technical-analysis-blueprint', title: 'Technical Analysis Blueprint', subtitle: 'Smart Chart Analysis', level: 'Beginner to advanced', duration: '20–25 hours', video: 'course-technical-analysis.mp4', description: 'Master technical analysis: read market trends, identify high-probability opportunities, and make data-driven decisions using charts, indicators, price action and professional trading strategies.', modules: technicalAnalysisModules },
  { slug: 'professional-options-trading', title: 'Professional Options Trading', subtitle: 'Options Trading Accelerator', level: 'Beginner to advanced', duration: '25–30 hours', video: 'course-options.mp4', description: 'Understand options contracts through advanced multi-leg strategies, Greeks, volatility analysis and risk management, so you can trade with discipline and confidence.', modules: optionsTradingModules },
  { slug: 'value-investing-blueprint', title: 'Value Investing Blueprint', subtitle: 'Smart Investing Through Fundamentals', level: 'Beginner to advanced', duration: '20–25 hours', video: 'course-value-investing.mp4', description: 'Learn how professional investors evaluate businesses, analyse financial statements, assess performance, determine intrinsic value and build a long-term portfolio using fundamental analysis.', modules: valueInvestingModules },
  { slug: 'professional-equity-research-analyst-program', title: 'Professional Equity Research Analyst Program', subtitle: 'Equity Research & Investment Analysis Certification', level: 'Intermediate to advanced', duration: '40–50 hours', video: 'course-equity-research.mp4', description: 'A career-focused program for aspiring equity research professionals covering research, valuation, report writing, compliance, ethics and the SEBI Research Analyst registration process.', modules: equityResearchModules },
  { slug: 'nism-xv-research-analyst-exam-prep', title: 'NISM XV Research Analyst Exam Prep', subtitle: 'Research Analyst Certification Prep (NISM XV)', level: 'Intermediate', duration: '35–45 hours', video: 'course-nism.mp4', description: 'Prepare for the NISM-Series-XV Research Analyst Certification Examination with full-syllabus coverage, practical case studies, financial analysis, valuation, regulations and exam-focused practice.', modules: nismModules },
].map((course) => ({ ...course, modules: course.modules.map((module, index) => typeof module === 'string' ? ({ title: module, topics: ['Core concepts and terminology', 'Practical market context', 'Guided examples and application'], outcome: `Build practical confidence with ${module.toLowerCase()}.`, duration: `${40 + (index % 3) * 10} min` }) : module) }));

const moduleGuides = {
  'Introduction to the Stock Market': ['Start with the purpose of a stock market before looking at prices. This chapter connects saving, investing, goals and the role of investors in long-term wealth creation.', 'Relate every concept to a personal financial goal and identify the investing myths that can lead to rushed decisions.'],
  'How the Stock Market Works': ['Follow the journey from a company raising money to an investor buying or selling its shares. The chapter makes the primary and secondary markets, exchanges and settlement cycle easier to connect.', 'Trace a familiar company listing and use the example to distinguish an IPO, FPO, bonus issue and rights issue.'],
  'Stock Market Participants': ['Markets work because several participants play different roles. Learn how investors, institutions, brokers, depositories and SEBI interact within the same market ecosystem.', 'Observe how FII and DII activity can influence sentiment, liquidity and short-term market movement.'],
  'Demat and Trading Account': ['Build the account foundation needed before placing an investment or trade. This chapter separates the role of your Demat account, trading account and linked bank account.', 'Follow the KYC and account-opening journey step by step, then review the charges and safeguards involved.'],
  'Types of Financial Instruments': ['Compare the major instruments available to an Indian investor instead of treating every investment as a stock. Learn what each option is designed to do inside a portfolio.', 'Match instruments to goals, time horizon and risk comfort before considering how they may fit together.'],
  'Understanding Stocks': ['Learn the language used to describe a company’s shares, valuation size and investment style. This chapter helps you classify stocks before deciding what deserves deeper research.', 'Practise sorting listed companies into market-cap and style categories using clear, repeatable criteria.'],
  'Understanding Stock Prices': ['Price moves are the result of buyers, sellers, liquidity and information meeting in real time. This chapter turns commonly seen market terms into practical observations.', 'Use a live Reliance price example to notice bid, ask, spread, volume, volatility and circuit limits in context.'],
  'Basic Fundamental Analysis': ['Move beyond headlines and learn the first set of numbers investors use to understand a business. Each measure is introduced as part of a wider company story.', 'Analyse a listed company with a simple checklist instead of relying on a single ratio or market tip.'],
  'Introduction to Technical Analysis': ['Learn how price information is displayed and how traders organise it into charts, time frames and technical reference points.', 'Read a live chart with a disciplined sequence: identify the chart, mark context, then observe indicators without treating them as predictions.'],
  'Order Types': ['Knowing how an order behaves is as important as knowing what to buy. This chapter explains the instructions you can give a broker and the risks each instruction helps manage.', 'Compare order types in a guided demo before using them with capital in a live market.'],
  'Risk Management': ['Strong investing starts with protecting capital. This chapter introduces risk-to-reward thinking, position sizing and the emotional discipline needed to follow a plan.', 'Create a basic risk framework that tells you how much to allocate, when to reduce exposure and why a stop loss may matter.'],
  'Long-Term Investing': ['Turn investing from an occasional action into a goal-led process. The chapter connects compounding, SIPs, portfolio building and asset allocation.', 'Use the ₹5,000 monthly investment example to see how regular contributions and time can work together.'],
  'Common Beginner Mistakes': ['Recognise the habits that can derail an otherwise sound plan, from reacting to rumours to taking too much risk without research.', 'Use each mistake as a checkpoint for building calmer decisions before placing the next order.'],
  'Live Market Demonstration': ['Bring the earlier concepts together in a guided live-market walkthrough. The focus is on observation, process and knowing what each screen element means.', 'Watch how market depth, price action and a first trade are reviewed in a structured workflow.'],
  'Building Your First Portfolio': ['Use all of the course foundations to create a portfolio with clear reasons behind each holding. This chapter moves from selecting stocks to monitoring and rebalancing them.', 'Complete the ₹1 lakh model portfolio assignment and explain diversification, allocation and exit choices in your own words.'],
};

const feedbackVideos = [
  { name: 'Yashi', url: 'https://youtube.com/shorts/TjuVVc2im7Q?si=ZienboG0uouFBPBf', portrait: '/assets/testimonials/yashi-cutout.png', message: 'Hear it in her own words.', theme: 'yashi' },
  { name: 'Anadi', url: 'https://youtube.com/shorts/R-BCmUC2Xn4?si=bsDnNTGyRAn4IEH5', portrait: '/assets/testimonials/anadi-cutout.png', message: 'Hear it in his own words.', theme: 'anadi' },
  { name: 'Amit', url: 'https://youtube.com/shorts/G7krrQzBoPA?si=W_u_MjEX72NU-xRn', portrait: '/assets/testimonials/amit-cutout.png', message: 'Hear it in his own words.', theme: 'amit' },
];

const mentors = [
  {
    firstName: 'Sushil Kumar', lastName: 'Kamboj', role: 'Managing Director · Smisha Share Market',
    image: '/assets/instructors/spotlight/sushil-kamboj-podium-v2.png',
    quote: '“Markets reward preparation, patience and a disciplined process. My goal is to help you understand the why behind every decision—and act with clarity.”',
    points: ['Strategic market guidance', 'Live practical examples', 'Disciplined decision-making'],
  },
  {
    firstName: 'Rahul', lastName: 'Kotkar', role: 'Trainer · Smisha Share Market',
    image: '/assets/instructors/spotlight/rahul-kotkar-podium.png',
    quote: '“Strong market habits begin with clear foundations. We break down every concept until you can use it with confidence.”',
    points: ['Clear core concepts', 'Guided practice', 'Learner-first support'],
  },
  {
    firstName: 'Nitin', lastName: 'Kumar', role: 'Manager · Smisha Share Market',
    image: '/assets/instructors/spotlight/nitin-kumar-podium.png',
    quote: '“Progress comes from following a process. Our focus is to make every learning step practical, structured and useful.”',
    points: ['Structured learning', 'Practical context', 'Progress support'],
  },
];

export default function CourseDetailPage({ slug }) {
  const course = courses.find((item) => item.slug === slug) ?? courses[0];
  const coursePace = /modules?/i.test(course.duration) ? 'Self-paced learning' : course.duration;
  const [activeModuleIndex, setActiveModuleIndex] = useState(0);
  const [activeMentorIndex, setActiveMentorIndex] = useState(0);
  const activeModule = course.modules[activeModuleIndex] ?? course.modules[0];
  const activeModuleGuide = moduleGuides[activeModule.title]?.[0] ?? activeModule.outcome;
  const testimonialTrackRef = useRef(null);
  const related = useMemo(() => courses.filter((item) => item.slug !== course.slug).slice(0, 3), [course.slug]);
  const outcomes = ['Understand the core concepts with clarity.', 'Apply each framework through guided examples.', 'Build a disciplined, repeatable market process.'];
  const scrollTestimonials = (direction) => testimonialTrackRef.current?.scrollBy({ left: direction * testimonialTrackRef.current.clientWidth * .82, behavior: 'smooth' });
  const activeMentor = mentors[activeMentorIndex];
  const selectMentor = (index) => setActiveMentorIndex((index + mentors.length) % mentors.length);
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;
    const timer = window.setInterval(() => setActiveMentorIndex((index) => (index + 1) % mentors.length), 6200);
    return () => window.clearInterval(timer);
  }, []);
  return <main className="course-detail-shell">
    <SiteHeader active="Courses" demoHref="#enquiry" />
    <section className={`course-detail-hero course-detail-hero--${course.slug}`}><video className="course-detail-atmosphere" src="/assets/courses/courses-hero-atmosphere.mp4" autoPlay muted loop playsInline preload="metadata" aria-hidden="true" /><div className="course-detail-atmosphere-shade" aria-hidden="true" /><div className="course-detail-hero-content"><a className="back-courses" href="/courses"><i className="fa-solid fa-arrow-left" /> All courses</a><h1 className="course-detail-accessible-title">{course.title}</h1><p>{course.subtitle}</p><p className="detail-hero-description">{course.description}</p><div className="detail-hero-meta"><span><i className="fa-solid fa-signal" /> {course.level}</span><span><i className="fa-regular fa-clock" /> {coursePace}</span><span><i className="fa-solid fa-layer-group" /> {course.modules.length} modules</span></div><div className="detail-hero-proof"><span><b>750+</b> learners in Pune</span><span><b>5 <i className="fa-solid fa-star" /></b> learning experience</span></div><div className="detail-hero-actions"><a className="detail-primary" href="#enquiry">Enrol in this course <i className="fa-solid fa-arrow-right" /></a><a className="detail-secondary" href={`/course-materials/${course.slug}-course-guide.pdf`} download>Download course guide <i className="fa-solid fa-download" /></a></div></div><CourseHeroVisual slug={course.slug} /></section>
    <section className="module-experience" id="curriculum" aria-labelledby="module-experience-title"><div className="module-grainient" aria-hidden="true"><Grainient color1="#eef9ff" color2="#b9e8ff" color3="#7d9ce7" timeSpeed={.14} warpStrength={.5} warpFrequency={3.2} warpSpeed={.28} warpAmplitude={44} blendAngle={-25} noiseScale={1.3} grainAmount={.018} contrast={1.03} saturation={.72} /></div><header><p className="section-label">COURSE CURRICULUM</p><h2 id="module-experience-title"><TextPressure text="See the complete path." /><br /><strong><TextPressure text="Focus on one step at a time." minWeight={700} /></strong></h2><p>Every module stays visible in one learning map. Choose any step to see its practical outcome and the topics it covers—without opening a long stack of accordions.</p></header><div className="curriculum-map" aria-label={`${course.title} curriculum`}><nav className="curriculum-navigator" aria-label="Select a course module"><div className="curriculum-navigator-heading"><span>LEARNING MAP</span><b>{course.modules.length} modules</b></div><div className="curriculum-module-grid">{course.modules.map((item, index) => <button className={index === activeModuleIndex ? 'is-active' : ''} type="button" key={item.title} onClick={() => setActiveModuleIndex(index)} aria-pressed={index === activeModuleIndex}><b>{String(index + 1).padStart(2, '0')}</b><span>{item.title}</span><i className="fa-solid fa-arrow-up-right-from-square" aria-hidden="true" /></button>)}</div></nav><article className="curriculum-focus" data-module={String(activeModuleIndex + 1).padStart(2, '0')} key={activeModule.title} aria-live="polite"><div className="curriculum-focus-top"><span><i className="fa-solid fa-compass" aria-hidden="true" /> Current module <b>{String(activeModuleIndex + 1).padStart(2, '0')} / {course.modules.length}</b></span><small><i className="fa-regular fa-clock" /> {activeModule.duration} <b>·</b> {activeModule.topics.length} topics</small></div><div className="curriculum-focus-heading"><p>Your next building block</p><h3>{activeModule.title}</h3></div><div className="curriculum-focus-intro"><b>Why this matters</b><p>{activeModuleGuide}</p></div><div className="curriculum-focus-outcome"><div className="curriculum-outcome-mark" aria-hidden="true"><svg viewBox="0 0 48 48" fill="none"><circle cx="24" cy="24" r="17.5" /><circle cx="24" cy="24" r="10" /><path d="M20.5 24.5 23 27l5-6" /></svg></div><div><b>By the end, you can</b><p>{activeModule.outcome}</p></div></div><div className="curriculum-focus-topics"><div className="curriculum-topics-heading"><p>WHAT YOU’LL WORK THROUGH</p><span>{activeModule.topics.length} concepts</span></div><ul>{activeModule.topics.map((topic) => <li key={topic}><i className="fa-solid fa-check" aria-hidden="true" />{topic}</li>)}</ul></div></article></div></section>
    <section className="learning-outcomes"><div className="outcome-title"><p className="section-label">WHAT YOU WILL GAIN</p><h2><TextPressure text="Learning built for " /><strong><TextPressure text="real decisions." minWeight={700} /></strong></h2></div><div className="outcome-cards">{outcomes.map((outcome, index) => <article key={outcome}><b>0{index + 1}</b><i className={["fa-solid fa-compass", "fa-solid fa-chart-line", "fa-solid fa-shield-halved"][index]} /><p>{outcome}</p></article>)}</div></section>
    <section className="instructor-section mentor-spotlight" aria-labelledby="mentor-spotlight-title"><div className="mentor-photo-stage"><div className="mentor-photo-track" style={{ transform: `translateX(-${activeMentorIndex * 100}%)` }}>{mentors.map((mentor, index) => <figure className="mentor-photo-slide" key={mentor.lastName} aria-hidden={index !== activeMentorIndex}><img src={mentor.image} alt={index === activeMentorIndex ? `${mentor.firstName} ${mentor.lastName} speaking at a Smisha Share Market event` : ''} loading={index === 0 ? 'eager' : 'lazy'} /></figure>)}</div><span className="mentor-photo-index"><b>{String(activeMentorIndex + 1).padStart(2, '0')}</b> / {String(mentors.length).padStart(2, '0')}</span></div><div className="mentor-spotlight-copy" key={activeMentor.lastName}><p className="section-label">LEARN WITH GUIDANCE</p><p className="mentor-copy-overline">SMISHA MENTOR SPOTLIGHT</p><h2 id="mentor-spotlight-title">{activeMentor.firstName} <strong>{activeMentor.lastName}</strong></h2><p className="instructor-role">{activeMentor.role}</p><blockquote className="instructor-quote">{activeMentor.quote}</blockquote><div className="instructor-points">{activeMentor.points.map((point) => <span key={point}><i className="fa-solid fa-check" /> {point}</span>)}</div><div className="mentor-spotlight-controls"><div className="mentor-dots" aria-label="Select a mentor">{mentors.map((mentor, index) => <button className={index === activeMentorIndex ? 'is-active' : ''} type="button" key={mentor.lastName} onClick={() => selectMentor(index)} aria-label={`Show ${mentor.firstName} ${mentor.lastName}`} aria-pressed={index === activeMentorIndex}><span>{String(index + 1).padStart(2, '0')}</span></button>)}</div><div className="mentor-arrows"><button type="button" onClick={() => selectMentor(activeMentorIndex - 1)} aria-label="Previous mentor"><i className="fa-solid fa-arrow-left" /></button><button type="button" onClick={() => selectMentor(activeMentorIndex + 1)} aria-label="Next mentor"><i className="fa-solid fa-arrow-right" /></button></div></div></div></section>
    <section className="course-testimonials"><div className="testimonial-heading"><div><p className="section-label">LEARNER EXPERIENCES</p><h2>See the journey in <strong>their own words.</strong></h2></div><div className="testimonial-nav" aria-label="Video testimonial navigation"><button type="button" onClick={() => scrollTestimonials(-1)} aria-label="Previous video testimonials"><i className="fa-solid fa-arrow-left" /></button><button type="button" onClick={() => scrollTestimonials(1)} aria-label="Next video testimonials"><i className="fa-solid fa-arrow-right" /></button></div></div><div className="testimonial-track" ref={testimonialTrackRef}>{feedbackVideos.map((video, index) => <article className="video-testimonial-card" key={video.name}><a className={`video-testimonial-media feedback-story-card feedback-story-card--${video.theme}`} href={video.url} target="_blank" rel="noreferrer" aria-label={`Watch ${video.name}'s feedback on YouTube`}><div className="feedback-story-copy"><small>SMISHA STUDENT STORY</small><strong>{video.name}</strong><p>{video.message}</p></div><div className="feedback-story-portrait"><img src={video.portrait} alt={video.name} loading={index ? 'lazy' : 'eager'} /></div><span className="feedback-story-play"><i className="fa-solid fa-play" aria-hidden="true" /> Watch feedback</span></a><div className="video-testimonial-copy"><span>SMISHA LEARNER · {String(index + 1).padStart(2, '0')}</span><h3>{video.name}&apos;s feedback</h3><p>Hear {video.name}&apos;s experience learning with Smisha Share Market.</p></div></article>)}</div></section>
    <section className="enquiry-section" id="enquiry"><div><p className="section-label">READY WHEN YOU ARE</p><h2>Find the right <strong>next step.</strong></h2><p>Tell us what you want to learn and our team will help you choose a suitable path.</p></div><form onSubmit={(event) => event.preventDefault()}><label>Your name<input required name="name" placeholder="Enter your name" /></label><label>Phone number<input required name="phone" inputMode="tel" placeholder="Enter your phone number" /></label><label>What would you like to know?<textarea name="message" rows="3" placeholder={`I'm interested in ${course.title}`} /></label><button className="detail-primary" type="submit">Send enquiry <i className="fa-solid fa-arrow-right" /></button></form></section>
    <section className="related-courses"><p className="section-label">KEEP LEARNING</p><h2>Explore related <strong>learning paths.</strong></h2><div className="course-grid related-course-grid">{related.map((item) => <a className="course-card course-card-link" href={`/courses/${item.slug}`} key={item.slug} aria-label={`View the ${item.title} course`}><div className="course-card-top"><div><p className="course-subtitle">{item.subtitle}</p><h3>{item.title}</h3><p className="course-description">{item.description}</p></div><span className="course-card-arrow" aria-hidden="true"><i className="fa-solid fa-arrow-right" /></span></div><CourseThumbnail slug={item.slug} className="course-media" /><div className="course-card-footer"><div className="course-meta"><span><i className="fa-solid fa-signal" /> {item.level}</span><span><i className="fa-solid fa-layer-group" /> {item.modules.length} modules</span></div><span className="course-details-button">View curriculum <i className="fa-solid fa-arrow-up-right-from-square" /></span></div></a>)}</div></section>
    <SiteFooter />
  </main>;
}
