'use client';

import { useMemo, useState } from 'react';
import { SiteFooter } from './SharedSiteSections';

const smartInvestingModules = [
  ['Introduction to the Stock Market', ['What is the Stock Market?', 'Why does the Stock Market exist?', 'History of the Indian Stock Market', 'Difference between Saving and Investing', 'Wealth Creation through Investing', 'Common Myths about Stock Market', 'Types of Investors', 'Financial Goals and Investing'], 'After completing this module, students will understand why stock markets exist and how they help in wealth creation.'],
  ['How the Stock Market Works', ['Primary Market', 'Secondary Market', 'IPO Explained', 'Follow-on Public Offer (FPO)', 'Rights Issue', 'Bonus Shares', 'Stock Exchanges', 'NSE vs BSE', 'Market Timings', 'Trading Holidays', 'Settlement Cycle (T+1)'], 'See how a company such as Tata Motors gets listed on NSE and how a trade moves through the market.'],
  ['Stock Market Participants', ['Retail Investors', 'Institutional Investors', 'Foreign Institutional Investors (FIIs)', 'Domestic Institutional Investors (DIIs)', 'Mutual Funds', 'Market Makers', 'Brokers', 'Depositories', 'Regulators (SEBI)'], 'Understand who participates in the market and how FIIs and DIIs can affect it.'],
  ['Demat and Trading Account', ['What is a Demat Account?', 'Trading Account', 'Bank Account Linkage', 'How Shares are Stored', 'Depository Participants', 'KYC Process', 'Opening an Account', 'Charges Explained'], 'Complete a practical, step-by-step walkthrough of opening a Demat account.'],
  ['Types of Financial Instruments', ['Equity Shares', 'Preference Shares', 'Bonds', 'Government Securities', 'ETFs', 'Mutual Funds', 'REITs', 'InvITs', 'Gold ETFs', 'Sovereign Gold Bonds'], 'Understand where each investment instrument fits in a portfolio.'],
  ['Understanding Stocks', ['What is a Share?', 'Face Value', 'Market Price', 'Market Capitalization', 'Large Cap', 'Mid Cap', 'Small Cap', 'Blue-chip Stocks', 'Growth Stocks', 'Value Stocks', 'Dividend Stocks'], 'Identify companies across stock categories and begin reading their market characteristics.'],
  ['Understanding Stock Prices', ['Why Prices Move', 'Demand & Supply', 'Circuit Limits', 'Upper Circuit', 'Lower Circuit', 'Volume', 'Liquidity', 'Volatility', 'Bid Price', 'Ask Price', 'Spread'], 'Use Reliance as a practical example to understand why prices can change every second.'],
  ['Basic Fundamental Analysis', ['Company Financial Statements', 'Revenue', 'Profit', 'EPS', 'PE Ratio', 'PB Ratio', 'ROE', 'Debt to Equity', 'Book Value', 'Cash Flow', 'Promoter Holding'], 'Analyse a listed company using a focused set of fundamental indicators.'],
  ['Introduction to Technical Analysis', ['Price Charts', 'Line Chart', 'Bar Chart', 'Candlestick Chart', 'Time Frames', 'Support', 'Resistance', 'Trend Lines', 'Moving Averages', 'RSI', 'MACD'], 'Read live charts and recognise the technical building blocks behind a market view.'],
  ['Order Types', ['Market Order', 'Limit Order', 'Stop Loss', 'Stop Limit', 'Bracket Order', 'Cover Order', 'GTT Orders', 'AMO Orders'], 'Place and compare different order types in a guided demo.'],
  ['Risk Management', ['Risk vs Reward', 'Position Sizing', 'Diversification', 'Portfolio Allocation', 'Stop Loss Strategy', 'Capital Protection', 'Emotional Discipline'], 'Protect capital before chasing profits by applying a practical risk framework.'],
  ['Long-Term Investing', ['Power of Compounding', 'SIP', 'Lump Sum Investing', 'Dividend Reinvestment', 'Goal-Based Investing', 'Portfolio Building', 'Asset Allocation'], 'Apply long-term investing principles to a ₹5,000 monthly investment over 20 years.'],
  ['Common Beginner Mistakes', ['FOMO Buying', 'Panic Selling', 'Overtrading', 'Tips & Rumours', 'Leverage Misuse', 'No Risk Management', 'Lack of Research'], 'Avoid the mistakes that most new investors make when they first enter the market.'],
  ['Live Market Demonstration', ['Reading Live Market', 'Understanding Market Depth', 'Identifying Trending Stocks', 'Watching Price Action', 'Placing Your First Trade'], 'Complete a live walkthrough of a trading platform with an instructor.'],
  ['Building Your First Portfolio', ['Selecting Stocks', 'Diversification', 'Sector Allocation', 'Rebalancing', 'Long-Term Strategy', 'Tracking Performance', 'Exit Strategy'], 'Create a ₹1 lakh model portfolio and explain the investment rationale behind it.'],
].map(([title, topics, outcome], index) => ({ title, topics, outcome, duration: `${35 + (index % 3) * 10} min` }));

const courses = [
  { slug: 'smart-investing-fundamentals', title: 'Smart Investing Fundamentals', subtitle: "Beginner's Guide to Stock Market", level: 'Beginner', duration: '15 modules', video: 'course-investing.mp4', description: 'Build a strong investing foundation—from how markets work and opening a Demat account to portfolio building, risk and live market practice.', modules: smartInvestingModules },
  { slug: 'mutual-fund-wealth-builder', title: 'Mutual Fund Wealth Builder', subtitle: 'Smart Mutual Fund Investing', level: 'Beginner to intermediate', duration: '10–15 hours', video: 'course-mutual-funds.mp4', description: 'Learn to compare fund categories, understand returns and risk, plan SIPs, manage taxes, and create a long-term, goal-led mutual fund portfolio.', modules: ['Introduction to Mutual Funds', 'Industry Participants', 'Types of Mutual Funds', 'Fund Documents', 'NAV & Returns', 'Risk & Performance Analysis', 'Choosing the Right Fund', 'SIP, STP & SWP', 'Taxation', 'Investment Process', 'Portfolio Construction', 'Mistakes to Avoid', 'Live Fund Analysis', 'Advanced Strategies'] },
  { slug: 'technical-analysis-blueprint', title: 'Technical Analysis Blueprint', subtitle: 'Professional Technical Trading', level: 'Beginner to advanced', duration: '20–25 hours', video: 'course-technical-analysis.mp4', description: 'Read charts with confidence. Move from chart fundamentals to candlesticks, price action, indicators, trade planning, and live market analysis.', modules: ['Introduction to Technical Analysis', 'Understanding Price Charts', 'Candlestick Analysis', 'Trend Analysis', 'Support & Resistance', 'Trendlines & Chart Patterns', 'Volume Analysis', 'Moving Averages', 'Momentum Indicators', 'Volatility Indicators', 'Fibonacci Analysis', 'Price Action Trading', 'Trading Strategies', 'Risk & Trade Management', 'Multi-Timeframe Analysis', 'Live Market Analysis'] },
  { slug: 'professional-options-trading', title: 'Professional Options Trading', subtitle: 'Advanced Options Strategies', level: 'Beginner to advanced', duration: '25–30 hours', video: 'course-options.mp4', description: 'Understand options from first principles through Greeks, volatility, strategy selection, hedging, disciplined execution, and trade management.', modules: ['Options Market Basics', 'Option Chain & Pricing', 'Option Greeks', 'Buying Options', 'Option Selling', 'Single-Leg Strategies', 'Multi-Leg Strategies', 'Volatility-Based Trading', 'Options Risk Management', 'Trading Psychology', 'Technical Analysis for Options', 'Live Options Workflow', 'Advanced Options Strategies'] },
  { slug: 'value-investing-blueprint', title: 'Value Investing Blueprint', subtitle: 'Equity Research & Fundamental Analysis', level: 'Beginner to advanced', duration: '20–25 hours', video: 'course-value-investing.mp4', description: 'Learn how investors evaluate businesses: financial statements, ratios, valuation, quality, industry context, and portfolio construction.', modules: ['Introduction to Fundamental Analysis', 'Businesses & Industries', 'Financial Statements', 'Income Statement Analysis', 'Balance Sheet Analysis', 'Cash Flow Analysis', 'Financial Ratios', 'Valuation Techniques', 'Qualitative Analysis', 'Annual Report Analysis', 'Economic & Industry Analysis', 'Stock Screening', 'Portfolio Construction', 'Live Company Analysis'] },
  { slug: 'professional-equity-research-analyst-program', title: 'Professional Equity Research Analyst Program', subtitle: 'Research Analyst Career Accelerator', level: 'Intermediate to advanced', duration: '40–50 hours', video: 'course-equity-research.mp4', description: 'A career-focused program covering research workflow, modelling, valuation, report writing, compliance, ethics and analyst career preparation.', modules: ['Introduction to Equity Research', 'Financial Markets', 'Business & Industry Analysis', 'Financial Statement Analysis', 'Ratio Analysis', 'Company Valuation', 'Financial Modeling', 'Research Report Writing', 'Technical Analysis', 'Economic & Macro Analysis', 'SEBI RA Regulations', 'Registration Process', 'Ethics & Standards', 'Research Tools', 'Practical Equity Research'] },
  { slug: 'nism-xv-research-analyst-exam-prep', title: 'NISM XV Research Analyst Exam Prep', subtitle: 'NISM XV Exam Success Program', level: 'Intermediate', duration: '35–45 hours', video: 'course-nism.mp4', description: 'Prepare systematically for the NISM-Series-XV exam with complete syllabus coverage, practical cases, mock tests and exam-focused revision.', modules: ['Research Analyst Profession', 'Securities Market', 'Financial Statement Analysis', 'Ratio Analysis', 'Company & Industry Analysis', 'Equity Valuation', 'Investment Decision Making', 'Economics & Macro Analysis', 'Technical Analysis', 'Research Report Writing', 'Legal & Regulatory Framework', 'Excel for Analysts', 'Mock Tests & Case Studies'] },
].map((course) => ({ ...course, modules: course.modules.map((module, index) => typeof module === 'string' ? ({ title: module, topics: ['Core concepts and terminology', 'Practical market context', 'Guided examples and application'], outcome: `Build practical confidence with ${module.toLowerCase()}.`, duration: `${40 + (index % 3) * 10} min` }) : module) }));

export default function CourseDetailPage({ slug }) {
  const course = courses.find((item) => item.slug === slug) ?? courses[0];
  const [activeModule, setActiveModule] = useState(0);
  const [language, setLanguage] = useState('English');
  const [openFaq, setOpenFaq] = useState(0);
  const module = course.modules[activeModule];
  const related = useMemo(() => courses.filter((item) => item.slug !== course.slug).slice(0, 3), [course.slug]);
  const outcomes = ['Understand the core concepts with clarity.', 'Apply each framework through guided examples.', 'Build a disciplined, repeatable market process.'];
  const faqs = [['Who is this course for?', `${course.title} is designed for ${course.level.toLowerCase()} learners who want a structured, practical path.`], ['Will I get practical learning?', 'Yes. Modules are designed to connect core concepts to market examples, exercises and guided application.'], ['How can I enquire?', 'Use the enquiry form below and the Smisha team will help you choose the right learning path.']];
  return <main className="course-detail-shell">
    <header className="site-header course-header"><a className="brand" href="/" aria-label="Smisha home"><img className="brand-logo" src="/assets/smisha-logo.png" alt="Smisha Share Market Classes" /><span className="brand-name">SMISHA <small>SHARE MARKET</small></span></a><nav className="desktop-nav course-nav" aria-label="Primary navigation"><a href="/">Homepage</a><a href="/#about">About Us</a><a className="active" href="/courses">Courses</a><a href="/#contact">Contact Us</a></nav><div className="header-actions"><a className="appointment" href="#enquiry">Book a<br />demo</a></div></header>
    <section className="course-detail-hero"><video autoPlay muted loop playsInline poster="/assets/smisha-coach.png"><source src={`/assets/courses/${course.video}`} /></video><div className="course-detail-hero-wash" /><div className="course-detail-hero-content"><a className="back-courses" href="/courses"><i className="fa-solid fa-arrow-left" /> All courses</a><p>{course.subtitle}</p><h1>{course.title}</h1><div className="detail-hero-meta"><span><i className="fa-solid fa-signal" /> {course.level}</span><span><i className="fa-regular fa-clock" /> {course.duration}</span><span><i className="fa-solid fa-layer-group" /> {course.modules.length} chapters</span></div><a className="detail-primary" href="#enquiry">Enquire now <i className="fa-solid fa-arrow-right" /></a></div></section>
    <section className="course-overview"><div><p className="section-label">A PRACTICAL LEARNING PATH</p><h2>Build confidence, <strong>one chapter at a time.</strong></h2></div><p>{course.description}</p></section>
    <section className="language-preview" aria-labelledby="language-preview-title"><div><p className="section-label">INTRODUCTION PREVIEW</p><h2 id="language-preview-title">Choose your <strong>preferred language.</strong></h2><p>Preview the course introduction in the language that feels most natural to you.</p><div className="language-tabs" role="tablist" aria-label="Intro video language">{['English', 'Hindi', 'Marathi', 'Gujarati'].map((item) => <button key={item} type="button" role="tab" aria-selected={language === item} className={language === item ? 'active' : ''} onClick={() => setLanguage(item)}>{item}</button>)}</div></div><div className="preview-player"><video controls poster="/assets/smisha-coach.png"><source src={`/assets/courses/${course.video}`} /></video><span>{language} course introduction</span></div></section>
    <section className="module-experience" aria-labelledby="module-experience-title"><header><p className="section-label">EXPLORE THE CURRICULUM</p><h2 id="module-experience-title">Your course, <strong>chapter by chapter.</strong></h2><p>Select a chapter to see its topics, learning outcome and practical focus.</p></header><div className="module-layout"><aside className="module-sidebar"><div className="module-sidebar-title"><span>Course modules</span><b>{course.modules.length}</b></div><div className="module-list" role="tablist" aria-label="Course modules">{course.modules.map((item, index) => <button key={item.title} role="tab" aria-selected={activeModule === index} className={activeModule === index ? 'active' : ''} onClick={() => setActiveModule(index)}><em>{String(index + 1).padStart(2, '0')}</em><span>{item.title}</span><i className="fa-solid fa-arrow-right" /></button>)}</div><div className="module-enquiry-card"><i className="fa-solid fa-comments" /><p>Need help choosing this course?</p><span>Talk with our learning advisor and get a clear next step.</span><a href="#enquiry">Talk to us <i className="fa-solid fa-arrow-right" /></a></div></aside><article className="module-detail" key={activeModule}><div className="module-detail-top"><span>CHAPTER {String(activeModule + 1).padStart(2, '0')}</span><small><i className="fa-regular fa-clock" /> {module.duration}</small></div><h3>{module.title}</h3><p className="module-outcome"><i className="fa-solid fa-bullseye" /> <span><b>Learning outcome</b>{module.outcome}</span></p><h4>Topics covered</h4><ul>{module.topics.map((topic) => <li key={topic}><i className="fa-solid fa-check" />{topic}</li>)}</ul><div className="chapter-preview"><span><i className="fa-solid fa-play" /> Chapter preview</span><p>See how this chapter turns concepts into a practical market skill.</p><a href="#enquiry">Request a demo <i className="fa-solid fa-arrow-right" /></a></div></article></div></section>
    <section className="learning-outcomes"><div className="outcome-title"><p className="section-label">WHAT YOU WILL GAIN</p><h2>Learning built for <strong>real decisions.</strong></h2></div><div className="outcome-cards">{outcomes.map((outcome, index) => <article key={outcome}><b>0{index + 1}</b><i className={["fa-solid fa-compass", "fa-solid fa-chart-line", "fa-solid fa-shield-halved"][index]} /><p>{outcome}</p></article>)}</div></section>
    <section className="instructor-section"><div className="instructor-photo"><img src="/assets/smisha-coach.png" alt="Smisha Share Market mentor" /></div><div><p className="section-label">LEARN WITH GUIDANCE</p><h2>Smisha <strong>Faculty Team</strong></h2><p>Learn from market educators and practitioner mentors who make complex market concepts clear, relevant and actionable.</p><div className="instructor-points"><span><i className="fa-solid fa-check" /> Practical examples</span><span><i className="fa-solid fa-check" /> Guided learning</span><span><i className="fa-solid fa-check" /> Doubt support</span></div></div></section>
    <section className="course-testimonials"><p className="section-label">LEARNER EXPERIENCES</p><h2>Confidence grows with <strong>guided practice.</strong></h2><div>{['“The structure made the market feel much more approachable.”', '“The practical examples helped me connect each concept to a decision.”', '“I now have a clear path for learning instead of jumping between tips.”'].map((quote, index) => <blockquote key={quote}><i className="fa-solid fa-quote-left" /><p>{quote}</p><footer>Smisha learner <span>0{index + 1}</span></footer></blockquote>)}</div></section>
    <section className="course-faq" aria-labelledby="course-faq-title"><p className="section-label">COURSE FAQs</p><h2 id="course-faq-title">Questions, <strong>clearly answered.</strong></h2>{faqs.map(([question, answer], index) => <details key={question} open={openFaq === index} onToggle={(event) => event.currentTarget.open && setOpenFaq(index)}><summary>{question}<i className="fa-solid fa-plus" /></summary><p>{answer}</p></details>)}</section>
    <section className="related-courses"><p className="section-label">KEEP LEARNING</p><h2>Explore related <strong>learning paths.</strong></h2><div>{related.map((item) => <a href={`/courses/${item.slug}`} key={item.slug}><video muted loop autoPlay playsInline><source src={`/assets/courses/${item.video}`} /></video><span>{item.subtitle}</span><h3>{item.title}</h3><small>Explore course <i className="fa-solid fa-arrow-right" /></small></a>)}</div></section>
    <section className="enquiry-section" id="enquiry"><div><p className="section-label">READY WHEN YOU ARE</p><h2>Find the right <strong>next step.</strong></h2><p>Tell us what you want to learn and our team will help you choose a suitable path.</p></div><form onSubmit={(event) => event.preventDefault()}><label>Your name<input required name="name" placeholder="Enter your name" /></label><label>Phone number<input required name="phone" inputMode="tel" placeholder="Enter your phone number" /></label><label>What would you like to know?<textarea name="message" rows="3" placeholder={`I'm interested in ${course.title}`} /></label><button className="detail-primary" type="submit">Send enquiry <i className="fa-solid fa-arrow-right" /></button></form></section>
    <SiteFooter />
  </main>;
}
